# Generated by Django 2.0 on 2018-01-30 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='trialbalance2017',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('debit', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('slug', models.CharField(default='description', max_length=100)),
            ],
        ),
    ]
